### ISSUE TITLE
Matrix Implementation

### ISSUE THREAD

**Issue by Dan00712** [Dan00712/math_linalg#2]
## TODO
- [ ] Container
    - [ ] ctor (__init__, __new__), dtor
    - !!**MATRIX NOT A SEQUENCE**!! => no sequence implementation
    - [ ] Index access
    - [ ] Row/Col view of Members
    - [ ] Sub-Matrix
        needed for determinant of matrix
- [ ] Matrix Ops
    - [ ] addition
    - [ ] subtraction
    - [ ] Scalar multiplication
    - [ ] Scalar division
    - [ ] Matrix Multiplication
- [ ] extended Matrix Ops
    - [ ] Determinant
    - [ ] Eigenvals
    - [ ] Eigenvecs
    - [ ] Vector add row/col operations
        usefull for gauss-jordan and other matrix operations

## Notes
- Should be inheritable
- C and backup Python Implementation
- Memory Safe (duh)
- C implementation prefixed by underscore and wrapped by python module
